import re
import warnings
from datetime import datetime
from difflib import SequenceMatcher
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

MISSING_TOKENS = {"", "nan", "none", "null", "na", "n/a", "-", "[]"}
DATE_TOKEN_PATTERN = re.compile(r"\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}")
REASON_SKIP_TOKENS = {"unknown", "unspecified"}
RECOMMENDATION_COLUMNS = [
    "Reasons for Hold",
    "Next Steps for Customer",
    "Next Steps for Underwriter",
    "Next Steps for Ops Team",
    "Next Steps for Customer Service",
]


st.set_page_config(
    page_title="Underwriting Issuance - Intelligent View",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown(
    """
    <style>
    .main-title {
        font-size: 2.2rem;
        font-weight: 700;
        color: #0f4c81;
        margin-bottom: 0.4rem;
    }
    .subtitle {
        color: #5c6770;
        margin-bottom: 1.3rem;
    }
    div[data-testid="stMetric"] {
        background: linear-gradient(145deg, #ffffff 0%, #eef5ff 100%);
        border: 1px solid #cfe0ff;
        border-radius: 14px;
        padding: 0.8rem 0.9rem;
        box-shadow: 0 8px 16px rgba(15, 76, 129, 0.12);
    }
    div[data-testid="stMetricLabel"] p {
        color: #0f4c81;
        font-weight: 700;
        letter-spacing: 0.1px;
    }
    div[data-testid="stMetricValue"] {
        color: #0b253a;
        font-size: 1.7rem;
        font-weight: 800;
    }
    div[data-testid="stMetricDelta"] {
        font-weight: 650;
    }
    .hero-kpi {
        background: linear-gradient(150deg, #eef5ff 0%, #ffffff 100%);
        border: 1px solid #cfe0ff;
        border-radius: 14px;
        padding: 0.95rem 1rem;
        box-shadow: 0 8px 16px rgba(15, 76, 129, 0.12);
        min-height: 180px;
    }
    .hero-kpi-title {
        color: #0f4c81;
        font-weight: 700;
        font-size: 0.98rem;
        margin-bottom: 0.2rem;
    }
    .hero-kpi-value {
        color: #0b253a;
        font-weight: 800;
        font-size: 2rem;
        line-height: 1.2;
        margin-bottom: 0.45rem;
    }
    .hero-kpi-sub {
        color: #35556d;
        font-size: 0.9rem;
        margin-bottom: 0.2rem;
    }
    </style>
    """,
    unsafe_allow_html=True,
)


@st.cache_data
def load_data(file_path_or_buffer):
    """Load CSV/Excel input."""
    try:
        if isinstance(file_path_or_buffer, str):
            if file_path_or_buffer.endswith(".csv"):
                return pd.read_csv(file_path_or_buffer, low_memory=False)
            if file_path_or_buffer.endswith((".xlsx", ".xls")):
                return pd.read_excel(file_path_or_buffer, engine="openpyxl")
            return None

        if file_path_or_buffer.name.endswith(".csv"):
            return pd.read_csv(file_path_or_buffer, low_memory=False)
        if file_path_or_buffer.name.endswith((".xlsx", ".xls")):
            return pd.read_excel(file_path_or_buffer, engine="openpyxl")
        return None
    except Exception as exc:
        st.error(f"Error loading file: {exc}")
        return None


@st.cache_data
def load_processed_fact_cases(output_folder="output"):
    """Load pre-processed fact_cases output generated by build_output_data.py."""
    fact_path = Path(output_folder) / "fact_cases.csv"
    if not fact_path.exists():
        return None

    try:
        df = pd.read_csv(fact_path, low_memory=False)
    except Exception:
        return None

    if "createDateTime" in df.columns:
        df["createDateTime"] = parse_datetime_series(df["createDateTime"])
    if "completedDateTime" in df.columns:
        df["completedDateTime"] = parse_datetime_series(df["completedDateTime"])

    for num_col in ["TAT_Days", "Hold_Count", "Total_Hold_Days"]:
        if num_col in df.columns:
            df[num_col] = pd.to_numeric(df[num_col], errors="coerce")

    for reason_col in ["Hold_Reasons_List", "All_Hold_Reasons_List"]:
        if reason_col in df.columns:
            df[reason_col] = df[reason_col].fillna("").apply(
                lambda s: parse_reason_history_cell(s, expected_count=None) if str(s).strip() else []
            )

    if "Hold_Days_List" in df.columns:
        def _to_float_list(value):
            vals = parse_separated_values(value) if str(value).strip() else []
            out = []
            for v in vals:
                try:
                    out.append(float(v))
                except Exception:
                    continue
            return out

        df["Hold_Days_List"] = df["Hold_Days_List"].fillna("").apply(_to_float_list)

    return df


@st.cache_data
def dataframe_to_csv_bytes(df):
    """Convert dataframe to CSV bytes for download."""
    export_df = df.copy()
    for list_col in ["Hold_Reasons_List", "All_Hold_Reasons_List", "Hold_Days_List"]:
        if list_col in export_df.columns:
            export_df[list_col] = export_df[list_col].apply(
                lambda v: "|".join(map(str, v)) if isinstance(v, list) else v
            )
    return export_df.to_csv(index=False).encode("utf-8")


def clean_text(value: object) -> str:
    if value is None or pd.isna(value):
        return ""
    text = str(value).strip().strip("[]")
    if not text or text.lower() in MISSING_TOKENS:
        return ""
    return text


def clean_tokens(tokens):
    out = []
    for token in tokens:
        item = str(token).strip()
        if not item or item.lower() in MISSING_TOKENS:
            continue
        out.append(item)
    return out


def parse_date_history_cell(value: object):
    text = clean_text(value)
    if not text:
        return []
    if "|" in text:
        return clean_tokens(text.split("|"))
    if "," in text:
        matches = DATE_TOKEN_PATTERN.findall(text)
        if matches:
            return clean_tokens(matches)
        return clean_tokens(re.split(r"\s*,\s*", text))
    return clean_tokens([text])


def parse_reason_history_cell(value: object, expected_count=None):
    text = clean_text(value)
    if not text:
        return []
    if "|" in text:
        return clean_tokens(text.split("|"))
    if "," in text:
        if expected_count is not None and expected_count <= 1:
            return clean_tokens([text])
        parts = clean_tokens(re.split(r"\s*,\s*", text))
        if expected_count is not None and expected_count > 1 and len(parts) != expected_count:
            return clean_tokens([text])
        return parts
    return clean_tokens([text])


def parse_separated_values(value):
    """Generic parser retained for compatibility."""
    return parse_reason_history_cell(value, expected_count=None)


def normalize_reason_text(value: object) -> str:
    text = clean_text(value).lower()
    if not text:
        return ""
    text = re.sub(r"[^a-z0-9]+", " ", text).strip()
    return re.sub(r"\s+", " ", text)


def reason_tokens(text: str):
    stop = {"for", "and", "the", "to", "of", "in", "on", "a", "an"}
    tokens = []
    for tok in text.split():
        t = tok.strip()
        if not t or t in stop:
            continue
        if len(t) > 4 and t.endswith("s"):
            t = t[:-1]
        tokens.append(t)
    return set(tokens)


def best_recommendation_key(reason_norm, rec_norm_values):
    if not reason_norm or not rec_norm_values:
        return None

    if reason_norm in rec_norm_values:
        return reason_norm

    contains_candidates = [rn for rn in rec_norm_values if (reason_norm in rn) or (rn in reason_norm)]
    if contains_candidates:
        return max(contains_candidates, key=len)

    rt = reason_tokens(reason_norm)
    best_key = None
    best_overlap = 0.0
    for rn in rec_norm_values:
        tt = reason_tokens(rn)
        if not rt or not tt:
            continue
        overlap = len(rt & tt) / max(len(rt), 1)
        if overlap > best_overlap:
            best_overlap = overlap
            best_key = rn
    if best_key is not None and best_overlap > 0:
        return best_key

    scored = [(SequenceMatcher(None, reason_norm, rn).ratio(), rn) for rn in rec_norm_values]
    scored.sort(reverse=True)
    if scored and scored[0][0] >= 0.58:
        return scored[0][1]
    return None


@st.cache_data
def load_recommendation_reference(path="recommendation.csv"):
    rec_path = Path(path)
    if not rec_path.exists():
        return pd.DataFrame(columns=RECOMMENDATION_COLUMNS)

    rec_df = pd.read_csv(rec_path)
    for col in RECOMMENDATION_COLUMNS:
        if col not in rec_df.columns:
            rec_df[col] = np.nan

    rec_df = rec_df[RECOMMENDATION_COLUMNS].copy()
    rec_df["__reason_norm"] = rec_df["Reasons for Hold"].apply(normalize_reason_text)
    rec_df = rec_df[rec_df["__reason_norm"].ne("")].drop_duplicates("__reason_norm", keep="first")
    return rec_df


def map_recommendations_for_display(reason_counts_df, recommendation_df):
    base_cols = [
        "onHoldReasonDescriptionsHistory",
        "Count",
        "Reasons for Hold",
        "Next Steps for Customer",
        "Next Steps for Underwriter",
        "Next Steps for Ops Team",
        "Next Steps for Customer Service",
    ]
    if reason_counts_df.empty:
        return pd.DataFrame(columns=base_cols)

    rec_by_norm = {}
    rec_norm_values = []
    if not recommendation_df.empty and "__reason_norm" in recommendation_df.columns:
        rec_by_norm = {row["__reason_norm"]: row for _, row in recommendation_df.iterrows()}
        rec_norm_values = list(rec_by_norm.keys())

    out_rows = []
    for _, row in reason_counts_df.iterrows():
        reason_text = row["Value"]
        reason_norm = normalize_reason_text(reason_text)
        matched = None

        best_key = best_recommendation_key(reason_norm, rec_norm_values)
        if best_key is not None:
            matched = rec_by_norm[best_key]

        out_rows.append(
            {
                "onHoldReasonDescriptionsHistory": reason_text,
                "Count": row["Count"],
                "Reasons for Hold": matched["Reasons for Hold"] if matched is not None else np.nan,
                "Next Steps for Customer": matched["Next Steps for Customer"] if matched is not None else np.nan,
                "Next Steps for Underwriter": matched["Next Steps for Underwriter"] if matched is not None else np.nan,
                "Next Steps for Ops Team": matched["Next Steps for Ops Team"] if matched is not None else np.nan,
                "Next Steps for Customer Service": matched["Next Steps for Customer Service"] if matched is not None else np.nan,
            }
        )

    return pd.DataFrame(out_rows, columns=base_cols)


def resolve_column(df, candidates):
    """Return the first matching column name from candidates."""
    for col in candidates:
        if col in df.columns:
            return col
    return None


def infer_case_type(hold_count):
    if hold_count <= 0:
        return "Straight Through"
    if hold_count == 1:
        return "One Touch"
    return f"Multi Hold ({int(hold_count)} touches)"


def create_tat_bucket(tat_days):
    if pd.isna(tat_days):
        return None
    if tat_days <= 4:
        return "1-4 days"
    if tat_days <= 7:
        return "5-7 days"
    return "7+ days"


def to_float_series(series):
    return pd.to_numeric(series, errors="coerce")


def parse_datetime_series(series):
    """Parse datetime safely and prefer day-first parse if it captures more values."""
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", UserWarning)
        parsed_dayfirst = pd.to_datetime(series, errors="coerce", dayfirst=True)
        parsed_default = pd.to_datetime(series, errors="coerce")

    if parsed_dayfirst.notna().sum() > parsed_default.notna().sum():
        return parsed_dayfirst
    return parsed_default


def parse_datetime_value(value):
    """Parse a single datetime value, preferring strict ISO before day-first parsing."""
    text = clean_text(value)
    if not text:
        return pd.NaT

    # Parse strict ISO first to avoid day-first misreads (e.g., 2025-03-01).
    if re.match(r"^\d{4}-\d{2}-\d{2}", text):
        iso_dt = pd.to_datetime(text, errors="coerce", dayfirst=False)
        if pd.notna(iso_dt):
            return iso_dt

    with warnings.catch_warnings():
        warnings.simplefilter("ignore", UserWarning)
        dt_dayfirst = pd.to_datetime(text, errors="coerce", dayfirst=True)
        dt_default = pd.to_datetime(text, errors="coerce")
    if pd.notna(dt_dayfirst):
        return dt_dayfirst
    return dt_default


def prepare_dataframe(df):
    """Prepare reusable analytic fields for the dashboard."""
    data = df.copy()

    create_col = resolve_column(data, ["createDateTime"])
    complete_col = resolve_column(data, ["completedDateTime"])
    history_reason_col = resolve_column(data, ["onHoldReasonDescriptionsHistory"])
    on_hold_dates_col = resolve_column(data, ["onHoldDatesHistory"])
    off_hold_dates_col = resolve_column(data, ["offHoldDatesHistory"])

    if create_col:
        data["createDateTime"] = parse_datetime_series(data[create_col])
    else:
        data["createDateTime"] = pd.NaT

    if complete_col:
        data["completedDateTime"] = parse_datetime_series(data[complete_col])
    else:
        data["completedDateTime"] = pd.NaT

    tat_from_dates = (
        data["completedDateTime"] - data["createDateTime"]
    ).dt.total_seconds() / 86400.0
    data["TAT_Days"] = tat_from_dates

    data.loc[data["TAT_Days"] < 0, "TAT_Days"] = np.nan
    data["TAT_Bucket"] = data["TAT_Days"].apply(create_tat_bucket)

    hold_reasons_list = []
    all_hold_reasons_list = []
    hold_days_list = []
    hold_counts_list = []
    global_last_completed_dt = data["completedDateTime"].dropna().max()

    for _, row in data.iterrows():
        history_text = row.get(history_reason_col, "") if history_reason_col else ""
        on_hold_raw = parse_date_history_cell(row.get(on_hold_dates_col, "")) if on_hold_dates_col else []
        off_hold_raw = parse_date_history_cell(row.get(off_hold_dates_col, "")) if off_hold_dates_col else []
        reasons = parse_reason_history_cell(history_text, expected_count=len(on_hold_raw) if on_hold_raw else None)

        reasons_for_top = parse_reason_history_cell(history_text, expected_count=None)
        all_hold_reasons_list.append(reasons_for_top)

        on_hold_dates = [parse_datetime_value(v) for v in on_hold_raw]
        off_hold_dates = [parse_datetime_value(v) for v in off_hold_raw]

        aligned_reasons = []
        aligned_days = []
        event_count = max(len(on_hold_dates), len(reasons))
        for idx in range(event_count):
            on_dt = on_hold_dates[idx] if idx < len(on_hold_dates) else pd.NaT
            if pd.isna(on_dt):
                continue

            reason_val = reasons[idx] if idx < len(reasons) else (reasons[-1] if reasons else "Unknown")
            reason_val = str(reason_val).strip() if str(reason_val).strip() else "Unknown"

            off_dt = off_hold_dates[idx] if idx < len(off_hold_dates) else pd.NaT
            if pd.notna(off_dt):
                end_dt = off_dt
            elif pd.notna(global_last_completed_dt):
                end_dt = global_last_completed_dt
            else:
                continue

            days = (end_dt - on_dt).total_seconds() / 86400.0
            if pd.notna(days) and days >= 0:
                aligned_reasons.append(reason_val)
                aligned_days.append(days)

        hold_reasons_list.append(aligned_reasons)
        hold_days_list.append(aligned_days)
        hold_counts_list.append(float(len(aligned_days)) if aligned_days else 1.0)

    data["Hold_Reasons_List"] = hold_reasons_list
    data["All_Hold_Reasons_List"] = all_hold_reasons_list
    data["Hold_Days_List"] = hold_days_list
    data["Total_Hold_Days"] = data["Hold_Days_List"].apply(lambda v: float(np.sum(v)) if v else 0.0)
    data["Hold_Count"] = pd.Series(hold_counts_list, index=data.index, dtype="float64").fillna(0).clip(lower=0)
    data["CaseType"] = data["Hold_Count"].apply(infer_case_type)

    data["Month"] = data["createDateTime"].dt.to_period("M")
    data["Month_Str"] = data["Month"].astype(str)
    data.loc[data["createDateTime"].isna(), "Month_Str"] = np.nan

    data["PrimaryHoldReason"] = data["All_Hold_Reasons_List"].apply(
        lambda v: v[0] if isinstance(v, list) and v else "Unknown"
    )

    return data


def apply_sidebar_filters(df):
    filtered = df.copy()

    st.sidebar.header("Data Source")
    st.sidebar.caption(f"Rows loaded: {len(df):,}")

    st.sidebar.header("Filters")

    if filtered["Month_Str"].notna().any():
        months = sorted(filtered["Month_Str"].dropna().unique().tolist())
        chosen_months = st.sidebar.multiselect(
            "Month-wise",
            options=months,
            default=months,
        )
        if chosen_months:
            filtered = filtered[filtered["Month_Str"].isin(chosen_months)]

    status_col = resolve_column(filtered, ["statusDescription"])
    if status_col:
        status_values = sorted(filtered[status_col].dropna().astype(str).unique().tolist())
        chosen_status = st.sidebar.multiselect(
            "Status",
            options=status_values,
            default=status_values,
        )
        if chosen_status:
            filtered = filtered[filtered[status_col].astype(str).isin(chosen_status)]

    req_col = resolve_column(filtered, ["requestTypeDescription"])
    if req_col:
        req_values = sorted(filtered[req_col].dropna().astype(str).unique().tolist())
        chosen_req = st.sidebar.multiselect(
            "Request Type",
            options=req_values,
            default=req_values,
        )
        if chosen_req:
            filtered = filtered[filtered[req_col].astype(str).isin(chosen_req)]

    lob_col = resolve_column(filtered, ["lineOfBusinessDescription"])
    if lob_col:
        lob_values = sorted(filtered[lob_col].dropna().astype(str).unique().tolist())
        chosen_lob = st.sidebar.multiselect(
            "Line Of Business",
            options=lob_values,
            default=lob_values,
        )
        if chosen_lob:
            filtered = filtered[filtered[lob_col].astype(str).isin(chosen_lob)]

    state_col = resolve_column(filtered, ["AgentBrokerStateCode"])
    if state_col:
        state_values = sorted(filtered[state_col].dropna().astype(str).unique().tolist())
        chosen_state = st.sidebar.multiselect(
            "Broker State",
            options=state_values,
            default=state_values,
        )
        if chosen_state:
            filtered = filtered[filtered[state_col].astype(str).isin(chosen_state)]

    case_type_filter = st.sidebar.radio(
        "Case Type",
        options=["All Cases", "Straight Through", "Hold Cases"],
        index=0,
    )
    if case_type_filter == "Straight Through":
        filtered = filtered[filtered["Hold_Count"] <= 0]
    elif case_type_filter == "Hold Cases":
        filtered = filtered[filtered["Hold_Count"] > 0]

    st.sidebar.caption(f"Rows after filters: {len(filtered):,}")
    return filtered


def top_counts(df, column_name, top_n=5):
    if column_name is None or column_name not in df.columns:
        return pd.DataFrame(columns=["Value", "Count"])

    series = (
        df[column_name]
        .fillna("Unknown")
        .astype(str)
        .str.strip()
        .replace("", "Unknown")
    )
    counts = series.value_counts().head(top_n).reset_index()
    counts.columns = ["Value", "Count"]
    return counts


def style_table_one_decimal(df, highlight_ge7_cols=None):
    styled = df.style
    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    if numeric_cols:
        styled = styled.format({col: "{:.1f}" for col in numeric_cols})

    if highlight_ge7_cols:
        for col in highlight_ge7_cols:
            if col in df.columns:
                styled = styled.apply(
                    lambda s: [
                        "background-color: #D32F2F; color: #FFFFFF; font-weight: 700;"
                        if pd.notna(v) and float(v) >= 7
                        else ""
                        for v in s
                    ],
                    subset=[col],
                )
    return styled


def build_top_table(df, col_candidates, title, top_n=5):
    col_name = resolve_column(df, col_candidates)
    table = top_counts(df, col_name, top_n=top_n)
    st.subheader(title)
    if table.empty:
        st.info("Column not available in current data.")
    else:
        st.dataframe(style_table_one_decimal(table), use_container_width=True, hide_index=True)


def build_top_table_with_tat(df, col_candidates, title, top_n=5):
    col_name = resolve_column(df, col_candidates)
    st.subheader(title)

    if col_name is None or col_name not in df.columns or "TAT_Days" not in df.columns:
        st.info("Column not available in current data.")
        return

    grouped = (
        df.assign(
            _group_val=df[col_name]
            .fillna("Unknown")
            .astype(str)
            .str.strip()
            .replace("", "Unknown")
        )
        .groupby("_group_val")
        .agg(
            Number_of_Cases=("TAT_Days", "size"),
            Avg_TAT_Days=("TAT_Days", "mean"),
        )
        .reset_index()
        .sort_values("Number_of_Cases", ascending=False)
        .head(top_n)
    )

    grouped = grouped.rename(columns={"_group_val": "Value"})
    styled_grouped = style_table_one_decimal(grouped, highlight_ge7_cols=["Avg_TAT_Days"])
    st.dataframe(styled_grouped, use_container_width=True, hide_index=True)


def build_top_hold_reason_with_tat(df, title, top_n=5):
    st.subheader(title)

    if "All_Hold_Reasons_List" not in df.columns or "TAT_Days" not in df.columns:
        st.info("Column not available in current data.")
        return

    records = []
    for _, row in df.iterrows():
        reasons = row.get("All_Hold_Reasons_List", [])
        tat = row.get("TAT_Days")
        if not isinstance(reasons, list) or pd.isna(tat):
            continue
        for reason in reasons:
            reason_text = str(reason).strip()
            if not reason_text:
                continue
            if reason_text.lower() in REASON_SKIP_TOKENS:
                continue
            records.append({"Value": reason_text, "TAT_Days": float(tat)})

    if not records:
        st.info("No onHoldReasonDescriptionsHistory values found.")
        return

    grouped = (
        pd.DataFrame(records)
        .groupby("Value")
        .agg(Number_of_Cases=("TAT_Days", "size"), Avg_TAT_Days=("TAT_Days", "mean"))
        .reset_index()
        .sort_values("Number_of_Cases", ascending=False)
        .head(top_n)
    )
    st.dataframe(style_table_one_decimal(grouped, highlight_ge7_cols=["Avg_TAT_Days"]), use_container_width=True, hide_index=True)


def top_counts_from_reason_list(df, top_n=15):
    records = []
    if "All_Hold_Reasons_List" not in df.columns:
        return pd.DataFrame(columns=["Value", "Count"])

    for _, row in df.iterrows():
        reasons = row.get("All_Hold_Reasons_List", [])
        if not isinstance(reasons, list):
            continue
        for reason in reasons:
            reason_text = str(reason).strip()
            if reason_text and reason_text.lower() not in REASON_SKIP_TOKENS:
                records.append(reason_text)

    if not records:
        return pd.DataFrame(columns=["Value", "Count"])

    series = pd.Series(records, dtype="object")
    counts = series.value_counts().head(top_n).reset_index()
    counts.columns = ["Value", "Count"]
    return counts


def build_hold_reason_impact(df):
    if "Hold_Reasons_List" not in df.columns or "Hold_Days_List" not in df.columns:
        return pd.DataFrame(columns=["onHoldReasonDescriptionsHistory", "Count", "Total_Hold_Days", "Avg_Hold_Days"])

    records = []
    for _, row in df.iterrows():
        reasons = row.get("Hold_Reasons_List", [])
        days = row.get("Hold_Days_List", [])
        if not isinstance(reasons, list) or not isinstance(days, list):
            continue
        for idx, reason in enumerate(reasons):
            if idx >= len(days):
                continue
            day_val = days[idx]
            if pd.isna(day_val):
                continue
            records.append({"onHoldReasonDescriptionsHistory": reason, "Hold_Days": float(day_val)})

    if not records:
        return pd.DataFrame(columns=["onHoldReasonDescriptionsHistory", "Count", "Total_Hold_Days", "Avg_Hold_Days"])

    reason_df = pd.DataFrame(records)
    impact_df = (
        reason_df.groupby("onHoldReasonDescriptionsHistory")
        .agg(
            Count=("Hold_Days", "size"),
            Total_Hold_Days=("Hold_Days", "sum"),
            Avg_Hold_Days=("Hold_Days", "mean"),
        )
        .reset_index()
        .sort_values("Total_Hold_Days", ascending=False)
    )
    impact_df["Total_Hold_Days"] = impact_df["Total_Hold_Days"].round(1)
    impact_df["Avg_Hold_Days"] = impact_df["Avg_Hold_Days"].round(1)
    return impact_df


def linear_sensitivity(x_series, y_series, min_samples=3):
    model_df = pd.DataFrame({"x": x_series, "y": y_series}).replace([np.inf, -np.inf], np.nan).dropna()
    if len(model_df) < min_samples or model_df["x"].nunique() < 2:
        return np.nan, np.nan, int(len(model_df))

    slope, _ = np.polyfit(model_df["x"], model_df["y"], 1)
    corr = model_df["x"].corr(model_df["y"])
    r2 = float(corr ** 2) if pd.notna(corr) else np.nan
    return float(slope), r2, int(len(model_df))


def build_monthly_shock_frame(filtered_df, completed_df):
    if completed_df.empty:
        return pd.DataFrame()

    monthly_completed = (
        completed_df.dropna(subset=["Month_Str"])
        .groupby("Month_Str")
        .agg(
            Mean_TAT_Days=("TAT_Days", "mean"),
            Avg_Touches=("Hold_Count", "mean"),
            Avg_Hold_Days_Per_Case=("Total_Hold_Days", "mean"),
            Hold_Case_Rate=("Hold_Count", lambda s: float((s > 0).mean() * 100.0)),
            SevenPlus_Rate=("TAT_Bucket", lambda s: float((s == "7+ days").mean() * 100.0)),
        )
        .reset_index()
    )

    monthly_all = (
        filtered_df.dropna(subset=["Month_Str"])
        .groupby("Month_Str")
        .agg(Open_Case_Rate=("completedDateTime", lambda s: float(s.isna().mean() * 100.0)))
        .reset_index()
    )

    monthly = monthly_completed.merge(monthly_all, on="Month_Str", how="left")
    return monthly.sort_values("Month_Str")


def suggest_action_for_reason(reason):
    text = str(reason).lower()

    rules = [
        (r"document|missing|incomplete|info", "Add a pre-submission document checklist and broker self-validation gate."),
        (r"validation|error|edit", "Introduce automated validation at intake with immediate correction prompts."),
        (r"system|issue|outage|technical", "Create an IT fast-lane escalation and fallback manual processing SOP."),
        (r"underwriting|review|approval", "Set SLA-based underwriting queue triage with daily aging review."),
        (r"write[- ]?out", "Standardize write-out templates and approval pathways to reduce waiting time."),
        (r"premium|pricing|rate", "Publish pricing exception rules and assign same-day approvers for edge cases."),
        (r"claim|loss", "Pre-fetch claim/loss data before assignment to avoid downstream hold cycles."),
    ]

    for pattern, action in rules:
        if re.search(pattern, text):
            return action

    return "Run weekly root-cause review, assign owner, and track closure date for repeat reasons."


def show_tat_bucket_distribution(completed_df):
    bucket_order = ["1-4 days", "5-7 days", "7+ days"]
    color_map = {
        "1-4 days": "#2E7D32",
        "5-7 days": "#FB8C00",
        "7+ days": "#D32F2F",
    }

    bucket_counts = completed_df["TAT_Bucket"].value_counts().reindex(bucket_order, fill_value=0)
    bucket_df = bucket_counts.reset_index()
    bucket_df.columns = ["TAT_Bucket", "Cases"]

    fig = px.bar(
        bucket_df,
        x="TAT_Bucket",
        y="Cases",
        color="TAT_Bucket",
        title="TAT Bucket Distribution (Overall Completed Cases)",
        color_discrete_map=color_map,
        category_orders={"TAT_Bucket": bucket_order},
    )
    fig.update_layout(showlegend=False)
    st.plotly_chart(fig, use_container_width=True)

    st.dataframe(style_table_one_decimal(bucket_df), use_container_width=True, hide_index=True)


def show_monthly_tat_buckets(completed_df):
    bucket_order = ["1-4 days", "5-7 days", "7+ days"]
    color_map = {
        "1-4 days": "#2E7D32",
        "5-7 days": "#FB8C00",
        "7+ days": "#D32F2F",
    }

    monthly_bucket = (
        completed_df.dropna(subset=["Month_Str", "TAT_Bucket"]) 
        .groupby(["Month_Str", "TAT_Bucket"]) 
        .size() 
        .reset_index(name="Cases")
    )
    monthly_bucket = monthly_bucket.sort_values("Month_Str")

    if monthly_bucket.empty:
        st.info("No monthly completed-case trend available.")
        return

    fig = px.area(
        monthly_bucket,
        x="Month_Str",
        y="Cases",
        color="TAT_Bucket",
        title="Primary TAT Buckets Over Time (Month-wise)",
        category_orders={"TAT_Bucket": bucket_order},
        color_discrete_map=color_map,
    )
    fig.update_xaxes(tickangle=45)
    st.plotly_chart(fig, use_container_width=True)


def render_tab_one(filtered_df):
    st.subheader("TAT Overview and 7+ Days Drilldown")

    left_col, right_col = st.columns([6, 4])
    tab1_df = filtered_df.copy()
    tab1_completed = tab1_df[tab1_df["TAT_Days"].notna()].copy()

    with left_col:
        with st.container(border=True):
            st.markdown("### TAT Overview")
            month_case_counts = (
                filtered_df.dropna(subset=["Month_Str"])
                .groupby("Month_Str")
                .size()
                .sort_index()
            )

            mean_tat = tab1_completed["TAT_Days"].mean()
            total_cases = len(tab1_df)
            avg_touches = tab1_df["Hold_Count"].mean()
            open_cases = int(tab1_df["completedDateTime"].isna().sum())
            closed_cases = int(tab1_df["completedDateTime"].notna().sum())

            current_count = len(tab1_df)
            delta_text = "No previous month"
            current_month_label = "Multiple/All"
            if len(month_case_counts) > 0:
                current_month_label = month_case_counts.index[-1]
                current_count = int(month_case_counts.iloc[-1])
                if len(month_case_counts) >= 2:
                    prev_month = month_case_counts.index[-2]
                    prev_count = int(month_case_counts.iloc[-2])
                    abs_change = current_count - prev_count
                    pct_change = (abs_change / prev_count * 100) if prev_count else np.nan
                    if pd.notna(pct_change):
                        delta_text = f"{abs_change:+,} ({pct_change:+.1f}%) vs {prev_month}"

            bucket_order = ["1-4 days", "5-7 days", "7+ days"]
            color_map = {
                "1-4 days": "#2E7D32",
                "5-7 days": "#FB8C00",
                "7+ days": "#D32F2F",
            }
            bucket_counts = (
                tab1_completed["TAT_Bucket"]
                .value_counts()
                .reindex(bucket_order, fill_value=0)
            )
            total_bucket_cases = int(bucket_counts.sum())

            kpi_col1, kpi_col2, kpi_col3, kpi_col4 = st.columns(4)
            kpi_col1.metric(
                "Aggregated Mean TAT",
                f"{mean_tat:.1f} days" if pd.notna(mean_tat) else "N/A",
            )
            kpi_col2.metric(
                "Avg Touches",
                f"{avg_touches:.1f}" if pd.notna(avg_touches) else "N/A",
            )
            kpi_col3.metric("Open Cases", f"{open_cases:,}")
            kpi_col4.metric("Closed Cases", f"{closed_cases:,}")
            st.caption(
                f"Total Number of Cases: {total_cases:,} | MoM Change: {delta_text} | Reference Month: {current_month_label}"
            )

            with st.container(border=True):
                st.markdown("##### Tat bucket distribution")
                if total_bucket_cases <= 0:
                    st.info("No completed cases available for bucket segmentation.")
                else:
                    segment_df = pd.DataFrame(
                        {
                            "TAT_Bucket": bucket_order,
                            "Count": [int(bucket_counts.get(b, 0)) for b in bucket_order],
                        }
                    )
                    segment_df["Percentage"] = segment_df["Count"] / total_bucket_cases * 100
                    segment_df["Pct_Text"] = segment_df["Percentage"].map(lambda v: f"{v:.1f}%")

                    fig_segment = go.Figure()
                    for _, row in segment_df.iterrows():
                        bucket = row["TAT_Bucket"]
                        pct = float(row["Percentage"])
                        fig_segment.add_trace(
                            go.Bar(
                                x=[pct],
                                y=[""],
                                orientation="h",
                                name=bucket,
                                marker_color=color_map[bucket],
                                text=[f"{pct:.1f}%" if pct > 0 else ""],
                                textposition="inside",
                                insidetextanchor="middle",
                                hovertemplate=f"TAT Bucket: {bucket}<br>Percentage: {pct:.2f}%<extra></extra>",
                            )
                        )
                    fig_segment.update_layout(
                        barmode="stack",
                        showlegend=True,
                        height=220,
                        margin=dict(l=4, r=4, t=8, b=4),
                        xaxis_title="",
                        yaxis_title="",
                        legend_title_text="TAT Bucket",
                        paper_bgcolor="rgba(0,0,0,0)",
                        plot_bgcolor="rgba(0,0,0,0)",
                    )
                    fig_segment.update_xaxes(range=[0, 100])
                    fig_segment.update_yaxes(showticklabels=False, showgrid=False, zeroline=False)
                    st.plotly_chart(fig_segment, use_container_width=True)

            st.markdown("#### TAT Bucket Distribution Over Time")
            monthly_bucket = (
                tab1_completed.dropna(subset=["Month_Str", "TAT_Bucket"])
                .groupby(["Month_Str", "TAT_Bucket"])
                .size()
                .reset_index(name="Count")
                .sort_values("Month_Str")
            )
            if monthly_bucket.empty:
                st.info("No completed-case monthly bucket data available.")
            else:
                fig_bucket_time = px.bar(
                    monthly_bucket,
                    x="Month_Str",
                    y="Count",
                    color="TAT_Bucket",
                    barmode="stack",
                    color_discrete_map=color_map,
                    category_orders={"TAT_Bucket": bucket_order},
                    title="TAT Bucket Distribution by Month",
                )
                fig_bucket_time.update_xaxes(tickangle=45)
                st.plotly_chart(fig_bucket_time, use_container_width=True)

            st.markdown("#### On-Hold Reason Impact in Days")
            reason_impact = build_hold_reason_impact(tab1_df)
            metric_cols = st.columns(2)
            total_reason_instances = int(reason_impact["Count"].sum()) if not reason_impact.empty else 0
            total_hold_days = float(reason_impact["Total_Hold_Days"].sum()) if not reason_impact.empty else 0.0
            metric_cols[0].metric("Total On-Hold Reason Occurrences", f"{total_reason_instances:,.1f}")
            metric_cols[1].metric("Total Hold Days Added/Taken", f"{total_hold_days:,.1f}")

            if reason_impact.empty:
                st.info("No on-hold reason day contribution data available.")
            else:
                styled_reason_impact = style_table_one_decimal(
                    reason_impact.head(10),
                    highlight_ge7_cols=["Avg_Hold_Days"],
                )
                st.dataframe(styled_reason_impact, use_container_width=True, hide_index=True)

    with right_col:
        with st.container(border=True):
            st.markdown("### 7+ Days Drilldown")
            with st.expander("Open 7+ Days Drilldown", expanded=False):
                high_tat = tab1_completed[tab1_completed["TAT_Bucket"] == "7+ days"].copy()

                if high_tat.empty:
                    st.info("No 7+ day completed cases available for selected filters/month.")
                    return

                top_cols = st.columns(3)
                top_cols[0].metric("7+ Day Cases", f"{len(high_tat):,}")
                top_cols[1].metric("Max TAT", f"{high_tat['TAT_Days'].max():.1f} days")
                top_cols[2].metric("Average TAT for 7+ TAT", f"{high_tat['TAT_Days'].mean():.1f} days")

                build_top_hold_reason_with_tat(
                    high_tat,
                    "Top 5 onHoldReasonDescriptionsHistory",
                    top_n=5,
                )
                build_top_table_with_tat(
                    high_tat,
                    ["bgiDescription"],
                    "Top 5 bgiDescription",
                )
                build_top_table_with_tat(
                    high_tat,
                    ["lineOfBusinessDescription"],
                    "Top 5 lineOfBusinessDescription",
                )
                build_top_table_with_tat(
                    high_tat,
                    ["AgentBrokerStateCode"],
                    "Top 5 AgentBrokerStateCode",
                )

                st.subheader("Top 5 High TAT Cases (Decreasing Order)")
                state_col = resolve_column(high_tat, ["AgentBrokerStateCode"])
                broker_num_col = resolve_column(high_tat, ["agentBrokerNum"])

                show_cols = [c for c in [broker_num_col, "TAT_Days", state_col] if c and c in high_tat.columns]

                if show_cols:
                    case_table = high_tat[show_cols].sort_values("TAT_Days", ascending=False).head(5).copy()
                    rename_map = {
                        broker_num_col: "agentBrokerNum",
                        "TAT_Days": "TAT",
                        state_col: "AgentBrokerStateCode",
                    }
                    case_table = case_table.rename(columns=rename_map)
                    st.dataframe(style_table_one_decimal(case_table), use_container_width=True, hide_index=True)
                else:
                    st.info("Required columns for high-TAT case listing are unavailable.")


def render_tab_two(filtered_df, completed_df):
    st.subheader("Hold-Centric Intelligence")

    # (a) Number of holds and distribution over TAT bucket over time
    monthly_holds = (
        completed_df.dropna(subset=["Month_Str", "TAT_Bucket"])
        .groupby(["Month_Str", "TAT_Bucket"])
        .agg(
            Avg_Holds=("Hold_Count", "mean"),
            Cases=("TAT_Days", "size"),
        )
        .reset_index()
        .sort_values("Month_Str")
    )

    if not monthly_holds.empty:
        trend_col, heat_col = st.columns(2)
        with trend_col:
            with st.container(border=True):
                st.markdown("### Holds Trend by TAT Bucket")
                fig_holds_trend = px.line(
                    monthly_holds,
                    x="Month_Str",
                    y="Avg_Holds",
                    color="TAT_Bucket",
                    markers=True,
                    title="Average Number of Holds Over Time by TAT Bucket",
                )
                fig_holds_trend.update_xaxes(tickangle=45)
                st.plotly_chart(fig_holds_trend, use_container_width=True)

        with heat_col:
            with st.container(border=True):
                st.markdown("### Holds Distribution Heatmap")
                pivot = monthly_holds.pivot(
                    index="TAT_Bucket", columns="Month_Str", values="Avg_Holds"
                )
                pivot = pivot.reindex(["1-4 days", "5-7 days", "7+ days"])

                fig_heat = px.imshow(
                    pivot,
                    text_auto=".2f",
                    aspect="auto",
                    color_continuous_scale="YlOrRd",
                    title="Holds Distribution Over TAT Buckets by Month",
                    labels=dict(x="Month", y="TAT Bucket", color="Avg Holds"),
                )
                st.plotly_chart(fig_heat, use_container_width=True)
    else:
        st.info("Not enough completed case data for hold-vs-TAT monthly distribution.")

    st.markdown("---")

    # (b) Hold reason distribution for on-hold cases
    status_col = resolve_column(filtered_df, ["statusDescription"])
    on_hold_mask = filtered_df["Hold_Count"] > 0
    if status_col:
        on_hold_mask = on_hold_mask | filtered_df[status_col].astype(str).str.contains("hold", case=False, na=False)

    on_hold_cases = filtered_df[on_hold_mask].copy()
    reason_col = resolve_column(on_hold_cases, ["onHoldReasonDescriptionsHistory", "PrimaryHoldReason"])

    reason_col1, reason_col2 = st.columns([1.4, 1])
    with reason_col1:
        with st.container(border=True):
            st.subheader("On-Hold Cases: Hold Reason Distribution")
            top_reasons = top_counts_from_reason_list(on_hold_cases, top_n=15)
            if top_reasons.empty:
                top_reasons = top_counts(on_hold_cases, reason_col, top_n=15)
            if top_reasons.empty:
                st.info("Hold reason column is unavailable.")
            else:
                fig_reason = px.bar(
                    top_reasons,
                    x="Value",
                    y="Count",
                    title="Top Hold Reasons (On-Hold Cases)",
                    labels={"Value": "Hold Reason", "Count": "Cases"},
                )
                fig_reason.update_xaxes(tickangle=45)
                st.plotly_chart(fig_reason, use_container_width=True)

    with reason_col2:
        with st.container(border=True):
            build_top_table_with_tat(
                filtered_df,
                ["AgentBrokerName", "AgentBrokerName__2", "agentBrokerNum"],
                "Top Brokers Handling Cases",
                top_n=10,
            )

    st.markdown("---")

    # (c) Top accountAnalyst, UnderWriter, and raterFullName taking 7+ days
    high_tat = completed_df[completed_df["TAT_Bucket"] == "7+ days"].copy()
    c1, c2, c3 = st.columns(3)
    with c1:
        with st.container(border=True):
            build_top_table_with_tat(
                high_tat,
                ["accountAnalyst", "accountAnalystName"],
                "Top accountAnalyst Taking 7+ TAT Days",
                top_n=10,
            )

    with c2:
        with st.container(border=True):
            build_top_table_with_tat(
                high_tat,
                ["underwriterName", "underwriter"],
                "Top UnderWriter Taking 7+ TAT Days",
                top_n=10,
            )

    with c3:
        with st.container(border=True):
            build_top_table_with_tat(
                high_tat,
                ["raterFullName"],
                "Top raterFullName Taking 7+ TAT Days",
                top_n=10,
            )

    st.markdown("---")

    # (d) Last month cases with highest TAT (top 5)
    st.subheader("Last Month: Highest TAT Cases (Top 5)")
    month_series = completed_df["Month_Str"].dropna().sort_values()
    if month_series.empty:
        st.info("No month data available for last-month high TAT cases.")
    else:
        last_month = month_series.iloc[-1]
        lm_df = completed_df[completed_df["Month_Str"] == last_month].copy()

        cols_requested = [
            resolve_column(lm_df, ["requestId"]),
            resolve_column(lm_df, ["processId"]),
            resolve_column(lm_df, ["AgentBrokerName", "AgentBrokerName__2"]),
            resolve_column(lm_df, ["accountAnalyst", "accountAnalystName"]),
            "TAT_Days",
            "TAT_Bucket",
        ]
        cols_requested = [c for c in cols_requested if c and c in lm_df.columns]

        if cols_requested:
            high_tat_lm = lm_df.sort_values("TAT_Days", ascending=False).head(5)[cols_requested].copy()
            rename_map = {
                "TAT_Days": "TAT",
                resolve_column(lm_df, ["requestId"]): "requestId",
                resolve_column(lm_df, ["processId"]): "processId",
                resolve_column(lm_df, ["AgentBrokerName", "AgentBrokerName__2"]): "AgentBrokerName",
                resolve_column(lm_df, ["accountAnalyst", "accountAnalystName"]): "accountAnalyst",
            }
            high_tat_lm = high_tat_lm.rename(columns=rename_map)
            st.caption(f"Last month in filtered data: {last_month}")
            st.dataframe(style_table_one_decimal(high_tat_lm), use_container_width=True, hide_index=True)
        else:
            st.info("Requested case-level columns not available.")

    st.markdown("---")

    # (e) Top on-hold reason and suggested actions
    st.subheader("Prescriptive Actions for Top Hold Reasons")
    reason_summary = top_counts_from_reason_list(on_hold_cases, top_n=10)
    if reason_summary.empty:
        reason_summary = top_counts(on_hold_cases, reason_col, top_n=10)
    if reason_summary.empty:
        st.info("Unable to generate hold reason actions because hold reason data is missing.")
    else:
        recommendation_df = load_recommendation_reference("recommendation.csv")
        if recommendation_df.empty:
            st.warning("recommendation.csv is missing or has no usable rows. Showing hold reasons without mapped actions.")
        action_df = map_recommendations_for_display(reason_summary, recommendation_df)
        st.dataframe(style_table_one_decimal(action_df), use_container_width=True, hide_index=True)


def render_tab_three(filtered_df, completed_df):
    st.subheader("Shock Simulator")

    if completed_df.empty:
        st.info("No completed cases available for TAT simulation.")
        return

    baseline_tat = float(completed_df["TAT_Days"].mean()) if completed_df["TAT_Days"].notna().any() else np.nan
    if pd.isna(baseline_tat):
        st.info("Baseline TAT is unavailable for current filter selection.")
        return

    monthly_shock = build_monthly_shock_frame(filtered_df, completed_df)

    kpi_specs = [
        {"label": "Avg Touches", "col": "Avg_Touches", "unit": ""},
        {"label": "Avg Hold Days per Case", "col": "Avg_Hold_Days_Per_Case", "unit": "days"},
        {"label": "Hold Case Rate", "col": "Hold_Case_Rate", "unit": "%"},
        {"label": "7+ Days Case Rate", "col": "SevenPlus_Rate", "unit": "%"},
        {"label": "Open Case Rate", "col": "Open_Case_Rate", "unit": "%"},
    ]

    baseline_values = {
        "Avg_Touches": float(filtered_df["Hold_Count"].mean()) if "Hold_Count" in filtered_df.columns else np.nan,
        "Avg_Hold_Days_Per_Case": float(filtered_df["Total_Hold_Days"].mean()) if "Total_Hold_Days" in filtered_df.columns else np.nan,
        "Hold_Case_Rate": float((filtered_df["Hold_Count"] > 0).mean() * 100.0) if "Hold_Count" in filtered_df.columns else np.nan,
        "SevenPlus_Rate": float((completed_df["TAT_Bucket"] == "7+ days").mean() * 100.0) if "TAT_Bucket" in completed_df.columns else np.nan,
        "Open_Case_Rate": float(filtered_df["completedDateTime"].isna().mean() * 100.0) if "completedDateTime" in filtered_df.columns else np.nan,
    }

    case_level_map = {
        "Avg_Touches": "Hold_Count",
        "Avg_Hold_Days_Per_Case": "Total_Hold_Days",
    }

    sensitivity_rows = []
    for spec in kpi_specs:
        kpi_col = spec["col"]
        slope = np.nan
        r2 = np.nan
        samples = 0
        model_type = "No model fit"

        if not monthly_shock.empty and kpi_col in monthly_shock.columns:
            slope, r2, samples = linear_sensitivity(monthly_shock[kpi_col], monthly_shock["Mean_TAT_Days"], min_samples=3)
            if pd.notna(slope):
                model_type = "Monthly sensitivity"

        if pd.isna(slope) and kpi_col in case_level_map:
            case_col = case_level_map[kpi_col]
            if case_col in completed_df.columns:
                slope, r2, samples = linear_sensitivity(completed_df[case_col], completed_df["TAT_Days"], min_samples=25)
                if pd.notna(slope):
                    model_type = "Case-level fallback"

        sensitivity_rows.append(
            {
                "KPI": spec["label"],
                "KPI_Column": kpi_col,
                "Baseline_Value": baseline_values.get(kpi_col, np.nan),
                "Sensitivity_Days_per_Unit": slope,
                "Model_R2": r2,
                "Samples_Used": samples,
                "Model_Type": model_type,
                "Unit": spec["unit"],
            }
        )

    sensitivity_df = pd.DataFrame(sensitivity_rows)
    if sensitivity_df.empty:
        st.info("No KPI sensitivity data available.")
        return

    left_col, right_col = st.columns([1, 2])
    with left_col:
        with st.container(border=True):
            st.markdown("### Scenario Input")
            selected_kpi = st.selectbox("KPI Driver", options=sensitivity_df["KPI"].tolist(), index=0)
            shock_pct = st.slider("Change in KPI (%)", min_value=-50, max_value=50, value=10, step=1)
            st.caption("Positive % means KPI increase. Negative % means KPI decrease.")

    selected_row = sensitivity_df[sensitivity_df["KPI"] == selected_kpi].iloc[0]
    base_kpi = selected_row["Baseline_Value"]
    scenario_kpi = base_kpi * (1.0 + shock_pct / 100.0) if pd.notna(base_kpi) else np.nan
    delta_kpi = scenario_kpi - base_kpi if pd.notna(base_kpi) and pd.notna(scenario_kpi) else np.nan

    slope = selected_row["Sensitivity_Days_per_Unit"]
    tat_impact = slope * delta_kpi if pd.notna(slope) and pd.notna(delta_kpi) else np.nan
    simulated_tat = max(0.0, baseline_tat + tat_impact) if pd.notna(tat_impact) else np.nan

    with right_col:
        with st.container(border=True):
            st.markdown("### Estimated TAT Impact")
            m1, m2, m3, m4 = st.columns(4)
            m1.metric("Baseline Mean TAT", f"{baseline_tat:.1f} days")
            m2.metric(
                "Simulated Mean TAT",
                f"{simulated_tat:.1f} days" if pd.notna(simulated_tat) else "N/A",
            )
            m3.metric(
                "Estimated Impact",
                f"{tat_impact:+.1f} days" if pd.notna(tat_impact) else "N/A",
            )
            m4.metric(
                "Model Strength (R²)",
                f"{selected_row['Model_R2']:.2f}" if pd.notna(selected_row["Model_R2"]) else "N/A",
            )

            scenario_df = pd.DataFrame(
                {
                    "Scenario": ["Baseline", "Simulated"],
                    "Mean_TAT_Days": [baseline_tat, simulated_tat if pd.notna(simulated_tat) else baseline_tat],
                }
            )
            fig_scenario = px.bar(
                scenario_df,
                x="Scenario",
                y="Mean_TAT_Days",
                color="Scenario",
                title="TAT Before vs After Shock",
                text="Mean_TAT_Days",
                color_discrete_map={"Baseline": "#1976D2", "Simulated": "#EF6C00"},
            )
            fig_scenario.update_traces(texttemplate="%{text:.1f}", textposition="outside")
            fig_scenario.add_hline(y=7, line_dash="dash", line_color="#D32F2F", annotation_text="7-day mark")
            st.plotly_chart(fig_scenario, use_container_width=True)

            unit = selected_row["Unit"]
            unit_suffix = unit if unit else "units"
            st.caption(
                f"{selected_kpi}: {base_kpi:.1f} -> {scenario_kpi:.1f} {unit_suffix} at {shock_pct:+.1f}% shock "
                f"| Model: {selected_row['Model_Type']} | Samples: {int(selected_row['Samples_Used'])}"
            )

    st.markdown("#### KPI Sensitivity Reference")
    ref_cols = ["KPI", "Baseline_Value", "Sensitivity_Days_per_Unit", "Model_R2", "Samples_Used", "Model_Type"]
    st.dataframe(style_table_one_decimal(sensitivity_df[ref_cols]), use_container_width=True, hide_index=True)
    st.caption("Sensitivity is estimated from current filtered data. Use this as directional what-if analysis, not a causal guarantee.")


def main():
    st.markdown('<div class="main-title">Underwriting Issuance - Intelligent View</div>', unsafe_allow_html=True)
    st.markdown(
        '<div class="subtitle">Reference logic retained, view redesigned into two decision tabs with 7+ day deep-dive and hold intelligence.</div>',
        unsafe_allow_html=True,
    )

    st.sidebar.header("Input")
    data_source = st.sidebar.radio(
        "Choose data source",
        ["Upload File", "Data Folder", "Processed Output Folder"],
        index=1,
    )

    source_df = None
    source_is_processed = False

    if data_source == "Upload File":
        uploaded_file = st.sidebar.file_uploader("Upload CSV/Excel", type=["csv", "xlsx", "xls"])
        if uploaded_file is not None:
            source_df = load_data(uploaded_file)
    elif data_source == "Data Folder":
        data_folder = Path("data")
        files = []
        if data_folder.exists():
            files = sorted(list(data_folder.glob("*.csv")) + list(data_folder.glob("*.xlsx")) + list(data_folder.glob("*.xls")))

        if files:
            selected_file = st.sidebar.selectbox("Select file from data folder", options=[f.name for f in files])
            if selected_file:
                source_df = load_data(str(data_folder / selected_file))
        else:
            st.sidebar.warning("No CSV/Excel files found in data folder.")
    else:
        output_folder = Path("output")
        source_df = load_processed_fact_cases(str(output_folder))
        source_is_processed = source_df is not None

        if source_df is None:
            st.sidebar.warning("No processed output found. Run build_output_data.py first.")
        else:
            st.sidebar.success("Loaded pre-processed output: output/fact_cases.csv")

    if source_df is None or source_df.empty:
        st.info("Please upload a file, select one from data folder, or use processed output folder.")
        return

    with st.spinner("Preparing data..."):
        if source_is_processed and {"TAT_Days", "Hold_Count", "TAT_Bucket", "Month_Str"}.issubset(source_df.columns):
            prepared_df = source_df.copy()
        else:
            prepared_df = prepare_dataframe(source_df)
        filtered_df = apply_sidebar_filters(prepared_df)

    if filtered_df.empty:
        st.warning("No records left after filters. Please widen filter selections.")
        return

    completed_df = filtered_df[filtered_df["TAT_Days"].notna()].copy()

    st.sidebar.header("CSV Report")
    report_filename = f"underwriting_filtered_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
    st.sidebar.download_button(
        label="Download Filtered Report (CSV)",
        data=dataframe_to_csv_bytes(filtered_df),
        file_name=report_filename,
        mime="text/csv",
    )

    tab1, tab2, tab3 = st.tabs(
        ["Tab 1 - TAT Overview", "Tab 2 - Hold Intelligence", "Tab 3 - Shock Simulator"]
    )

    with tab1:
        render_tab_one(filtered_df)

    with tab2:
        render_tab_two(filtered_df, completed_df)

    with tab3:
        render_tab_three(filtered_df, completed_df)


if __name__ == "__main__":
    main()
